[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/laravel/artisan queue:work redis --sleep=3 --tries=3 --timeout=90
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/laravel/storage/logs/worker.log
stopwaitsecs=60

[program:laravel-mail-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/laravel/artisan queue:work redis --queue=mail --sleep=3 --tries=3 --timeout=90 || sleep 30
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/laravel/storage/logs/mail-worker.log
stopwaitsecs=60
