[program:laravel-scheduler]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/laravel/artisan schedule:work
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/var/www/html/laravel/storage/logs/scheduler.log
